* TODO Притащить на работу шалфея
SCHEDULED: <2017-06-02 Fri .+1w>

* DONE Записать про грипп
CLOSED: [2017-07-17 Mon 14:13]

* DONE Фидбек Теле2
CLOSED: [2017-06-15 Thu 19:04]

* Узнать координаты
* Найти скриншот с пред. обр.

* Система "Батисакаф"

Запись из глаз
Угол обзора
Виньетки
Засветы и затемнения (память сетчатки)
Полное погружение
Звук в реальном времени
Акустический гиперспектр
Расширенный динамический диапазон
Возможность нарисовать на экране направляющие пальцем
Эффект "ресниц" на огнях
Имитаторы артефактов стекловидного тела
Воспроизведение на нескольких экранах ("боковое зрение")
Мгновенная запись или постоянная запись или буфер предзаписи

* DONE SPK для Degeneradio
CLOSED: [2017-06-15 Thu 19:04]

* DONE Посмотреть пароль от контача
CLOSED: [2017-07-17 Mon 14:12] DEADLINE: <2017-06-15 Thu 20:01> SCHEDULED: <2017-06-15 Thu 20:03>

* DONE Слева от входа в комнату лежат пласмаски от коляски. Присобачить их к коляске.
CLOSED: [2017-07-17 Mon 14:13] SCHEDULED: <2017-06-16 Fri .+1w>

* Библия

170717 == Не то чтоб прямо библия, но некоторая связанная мистема взглядов.

* Роспотребнадзор

1. На сайте и инфощите и где бы о ни было нет информации о том, что часть пути преодолевается на автобусе.
2. Надостаточно ярко указано, что отплытие не от пристани в Иркутске, а от пристани в листвянке, поэтому в 6-30 утра мы попали в неприятную ситуацию. Вместе с нами немцы. От охранников узнали, что подобные инциденты происходят нередко. По распросам пассажиров оказалось, что людям пришлось отложить трип на неделю и им в кассе при продаже билетов не сказали, что отход не гт пристани.
3. На сайте сказано, что билеты принимаются обратно не позднее часа после отправления. Если отход в 7, а касса открывается в 8, то пароходство 100% стоимости билетов. Даже если билеты сданы, пароходство получает 25% их стоимости (уточнить).
4. Мы попали в шокирующую ситуацию, требуем возврата стоимости одного билета (3500 плюс такси 300) иначе обращаемся через суд, с привлечением прессы.

Переношу в гмейл.

* TODO Купить укитаз ирригатор браслет
* TODO Активировать карту Оби
